### ISSUE TITLE
Change code to use proper package structure

### ISSUE THREAD

**Issue by andrewberls** [UCSB-CS56-Projects/cs56-utilities-credit-card-validator#1]
The code does not currently use any sort of package structure The code and directory structure should be modified to reflect the new style: `src/edu/ucsb/cs56/projects/utilities/credit_card_validator`, corresponding to a package name of `edu.ucsb.cs56.projects.utilities.credit_card_validator`

~estimated 50

**Comment by jaeaster** [comment]
Done. Edited build.xml to reflect this change as well
