### ISSUE TITLE
Convert to Web Application

### ISSUE THREAD

**Issue by jaeaster** [UCSB-CS56-Projects/cs56-utilities-credit-card-validator#13]
Host the program on heroku and convert the GUI to an html form.

Bootstrap is a great front-end framework to use in order to make the app look aesthetically pleasing.
http://getbootstrap.com/

**Comment by jaeaster** [comment]
Approved ~500 points

**Comment by jaeaster** [comment]
W16 approved

**Comment by jimmylle** [comment]
F16 OK (300 pts)
