### ISSUE TITLE
Validity of length and character input

### ISSUE THREAD

**Issue by stefanagloginic** [UCSB-CS56-Projects/cs56-utilities-credit-card-validator#15]
Have a check for user input in JTextField concerning the amount of digits input and characters input. For example, if digits put are less than/greater than that specific credit cards length have label show up alerting user of their error. Display also shows up of how much the user went over.
Once user validates card, another JLabel will tell user they used characters other than digits. Output characters used.

**Comment by jaeaster** [comment]
200 points

**Comment by jaeaster** [comment]
Closed
