### ISSUE TITLE
Enter key causes validation of card number

### ISSUE THREAD

**Issue by stefanagloginic** [UCSB-CS56-Projects/cs56-utilities-credit-card-validator#16]
When the user clicks enter, instead of having it do nothing, it can initiate the validate button. If the length is under/over then a JLabel would show up telling the user and the validate button would not be clicked. After the enter key is hit, the asterisks disappear. This also occurs when user tries to validate a card number.

**Comment by jaeaster** [comment]
200 points

**Comment by jaeaster** [comment]
Closed
