### ISSUE TITLE
Add a GUI

### ISSUE THREAD

**Issue by andrewberls** [UCSB-CS56-Projects/cs56-utilities-credit-card-validator#2]
Right now the project only provides a command-line interface for generating and validating numbers. There should be a GUI interface with buttons allowing the user to choose between generating/validating, as well as a text input to allow them to type or paste in a number to validate.

~estimated 350

**Comment by jaeaster** [comment]
Finished GUI. Added two buttons to validate and generate card numbers, one text field to get input and display text, one combobox to retrieve desired card type.
