### ISSUE TITLE
Java Spark Spike!

### ISSUE THREAD

**Issue by jaeaster** [UCSB-CS56-Projects/cs56-utilities-credit-card-validator#24]
In agile software development, a "spike" is research done on a story that cannot be estimated until a development team runs a timeboxed investigation.

Complete a spike on the Java Spark web framework http://sparkjava.com/

Take a look at the following pages:

http://sparkjava.com/download

And then answer these questions:

* What is the default recommended build tool for Spark?
* At what URL can you find the hello world example if you run a local server?
* What are the three basic components of an http route in Spark?

100 points

Bonus question (Extra 100 points):

* What are the two variables you get access to in the callback of a route function?
Furthermore, what is a route function and what is the significance of the callback?

**Comment by derenlei** [comment]
Answers:
- Maven
- http://localhost:4567/hello
- 1. A **verb** (get, post, put, delete, head, trace, connect, options);   
  2. A **path** (/hello, /users/:name);   
  3. A **callback** (request, response) -> { }

**Comment by jaeaster** [comment]
Granted 100 pts - JE

This issue was easier than I thought.
