### ISSUE TITLE
Add support for choosing different issuing networks

### ISSUE THREAD

**Issue by andrewberls** [UCSB-CS56-Projects/cs56-utilities-credit-card-validator#3]
Credit card numbers have different fields with different meanings. For example the first digit signifies the "system", e.g. Visa or Mastercard. For each of these systems, the numbers have different structure and meanings. The app should give the user the ability to choose between systems such as American Express / Visa / Mastercard, and generate valid numbers for each.

There is information available on how the numbers are structured [here](http://money.howstuffworks.com/personal-finance/debt-management/credit-card1.htm) and [here](http://www.getcreditcardnumbers.com/).

~estimated 200

**Comment by jaeaster** [comment]
Added support to choose an issuing network. Users can now pick between Visa, Amex, Mastercard, and Discover.
