### ISSUE TITLE
Add asterisk character view support

### ISSUE THREAD

**Issue by jaeaster** [UCSB-CS56-Projects/cs56-utilities-credit-card-validator#8]
Currently when a user is inputting their credit card number, the actual numbers show up. Similar to how passwords are displayed upon input, the user should have an option to show the credit card number digits as asterisks "*" as opposed to actual digits.

ex) 1234567890123456 should show as:
      ********************

**Comment by jennacryan** [comment]
approved
~300 points

**Comment by jaeaster** [comment]
Closed
